### ISSUE TITLE
[FeedBack] console error link map is not functioning to close, tag etc

### ISSUE THREAD

**Issue by Claire** [GarinZ/link-map#91]
Thank you for submitting an issue for Link Map. To help us better understand your feedback, please fill out the following template(If you think it's too complicated, just write down whatever you want):

## Description
I tried closing a window from linkmap, and names in the tree greyout but the window and tabs stay open. an debug console shows
```
tree.js:10 Uncaught Error: Attempting to use a disconnected port object
    at lD.sendMessage (tree.js:10:199754)
    at Ey.insertTag (tree.js:2011:15693)
    at k.fn.init.callback (tree.js:1992:13699)
    at HTMLLIElement.itemClick (tree.js:2015:43251)
    at HTMLDocument.dispatch (tree.js:2040:39233)
    at g.handle (tree.js:2040:37219)
```
## Expected behavior
Chrome window to close and all tabs in it to close
## Actual behavior
window and tabs stay open.
## Additional information
Pro account, version
1.1.5
Thank you for fixing the issue :)

**Comment by olibye** [comment]
I get the following, similar, stack trace when trying to close a window using the (x) from the link map window.
I have to work around this by closing the window using the close button (MacOS red dot) on the browser window itself.

```
tree.js:10 Uncaught Error: Attempting to use a disconnected port object
    at lD.sendMessage (tree.js:10:199754)
    at Ey.closeNodes (tree.js:2011:12280)
    at Ey.onClick (tree.js:2011:10581)
    at e.<computed>.<computed>._trigger (tree.js:2022:7740)
    at D._triggerNodeEvent (tree.js:2015:111500)
    at HTMLUListElement.<anonymous> (tree.js:2015:138841)
    at HTMLUListElement.dispatch (tree.js:2040:39233)
    at g.handle (tree.js:2040:37219)
